name: Mirko
favicon: null
layout_spectrum: 0.6114281257614493
typography_spectrum: 0.013739673420786858
title: Hello World
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7725883824750781
  lightness: 0.6754148039035499
  saturation: 0.6705849531572312
  rhythmicContrast: 0.7072077845223248
purpose: []
